m1=matrix(1:20,nrow=5,ncol=4)
print(m1)
rnames = c("Row1", "Row2", "Row3")
cnames = c("Col1", "Col2", "Col3")
m2 = matrix(11:19, nrow=3, ncol=3, byrow=TRUE, dimnames=list(rnames, cnames))
print("3 × 3 matrix with labels, filled by rows: ")
print(m2)
rwnames = c("Row1", "Row2")
clnames = c("Col1", "Col2")
print("2 × 2 matrix with labels, filled by columns: ")
m3 = matrix(5:8, nrow=2, ncol=2, byrow=FALSE, dimnames=list(rwnames, clnames))
print(m3)
